services:
  mysql:
    image: mysql:8.0
    container_name: my-portfolio-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: GbSY5TH8q9+mYEIEWtVylCP98pm6eDhpTDlmY9AF2w8=
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: MplEywmZIxUdSQfq/GxB4rSTXrCqlgpU04Qwr2eMMBY=
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: